config/routes.rb
Rails.application.routes.draw do
  root "library#home"

  get "/", to: "library#home"
  get "/books", to: "books#show"
  get "/book", to: "books#add"
  post "/book", to: "books#create"
  get "/book/edit", to: "books#edit"
  put "/book/edit", to: "books#update"
  get "/book/remove", to: "books#remove"
  delete "/book/remove", to: "books#delete"
  get "/admin", to: "sessions#new"
  post "/admin", to: "sessions#create"
  get "/logout", to: "sessions#delete"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books

  before_save do
    self.name = name.downcase
  end
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  after_find :titleize_name

  private

  def titleize_name
    self.name = name.split("-").map(&:titleize).join("-")
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :owner
  belongs_to :author
  has_and_belongs_to_many :genres
  has_one :book_embedding

  before_save do
    self.title = title.downcase
  end
  before_destroy :destroy_genres, :destroy_embedding
  after_destroy :destroy_owner, :destroy_author
  validates :title, presence: true, length: { minimum: 4, maximum: 200 }

  def to_s
    owner = self.owner.name
    author = self.author.name
    genres = self.genres.map(&:name).join(", ")
    "#{owner} owns #{title} written by #{author} under the genres of #{genres}"
  end

  private

  def destroy_owner
    owner.destroy unless owner.books.where.not(id: self).present?
  end

  def destroy_author
    author.destroy unless author.books.where.not(id: self).present?
  end

  def destroy_embedding
    book_embedding&.destroy
  end

  def destroy_genres
    genres.each do |genre|
      genre.destroy unless genre.books.where.not(id: self).present?
    end
  end
end

app/models/book_embedding.rb
class BookEmbedding < ApplicationRecord
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :books
  before_save do
    self.name = name.downcase
  end
  validates :name, length: { minimum: 3, maximum: 50 }
  after_find :titleize_name

  private

  def titleize_name
    self.name = name.split("-").map(&:titleize).join("-")
  end
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :books

  before_save do
    self.name = name.downcase
  end
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  after_find :titleize_name

  private

  def titleize_name
    self.name = name.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.name = name.downcase }
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  has_secure_password
  VALID_PASSWORD_REGEX = /(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}/
  validates :password, presence: true, length: { minimum: 10 }, format: { with: VALID_PASSWORD_REGEX }

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  add_flash_types :notice, :danger
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include SessionsHelper

  before_action :authenticate_user, except: [:show]

  def show
    @owners = Owner.all.sort_by(&:name)
    @authors = Author.all.sort_by(&:name)
    @genres = Genre.all.sort_by(&:name)
    @owner = Owner.find_by(id: params[:owner].presence)
    @author = Author.find_by(id: params[:author].presence)
    @genre = Genre.find_by(id: params[:genre].presence)
    @books = Book.paginate(page: params[:page], per_page: 10)

    # Filter based on search & selectors, allowing for multiple filters
    @books = @books.where("title LIKE ?", "%#{params[:title].downcase}%") if params[:title].present?
    @books = @books.where(owner: @owner) unless @owner.nil?
    @books = @books.where(author: @author) unless @author.nil?
    @books = @books.where.associated(:genres).where(genres: { id: @genre }) unless @genre.nil?
  end

  def add
  end

  def create
    book = Book.new(title: params[:title].strip)
    book.owner = Owner.find_or_create_by(name: params[:owner].strip.downcase)
    book.author = Author.find_or_create_by(name: params[:author].strip.downcase)
    book.genres = params[:genres].split(",").map { |genre| Genre.find_or_create_by(name: genre.strip.downcase) }
    book.save!
    EmbedBookJob.perform_later(book)
    redirect_to books_path, notice: "\"#{book.title.titleize}\" has been added"
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.title = params[:book][:title].strip
    @book.owner = Owner.find_or_create_by(name: params[:book][:owner].strip.downcase)
    @book.author = Author.find_or_create_by(name: params[:book][:author].strip.downcase)
    @book.genres = params[:book][:genres].split(",").map { |genre| Genre.find_or_create_by(name: genre.strip.downcase) }
    if @book.save
      EmbedBookJob.perform_later(@book)
      redirect_to books_path, notice: "\"#{@book.title.titleize}\" has been updated"
    else
      flash.now[:danger] = "Failed to update \"#{@book.title.titleize}\""
      render :edit
    end
  end

  def remove
    @book = Book.find(params[:id])
  end

  def delete
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path, notice: "\"#{@book.title.titleize}\" has been removed"
    else
      flash.now[:danger] = "Failed to remove \"#{@book.title.titleize}\""
      render :remove
    end
  end
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:username].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_to books_path, notice: "Welcome back, #{user.name.titlecase}!"
    else
      flash.now[:danger] = "Invalid username/password combination"
      render "new", status: :unprocessable_entity
    end
  end

  def delete
    log_out
    redirect_to root_path, notice: "Come back soon!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = "")
    base_title = "Churchill Library"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/chat_helper.rb
module ChatHelper
  # Special error for when messages added out of order
  class MessageOrderError < StandardError
    attr_reader :message

    def initialize(message = nil)
      super(message)
      @message = message
    end
  end

  # Tracks the messages between the user & assistant in a conversation
  class Conversation
    attr_reader :messages

    def initialize
      @messages = []
    end

    def add_user_message(content)
      unless @messages.empty? || @messages.last[:role] == "assistant"
        raise ChatHelper::MessageOrderError, "expecting assistant message"
      end

      @messages.push({ role: "user", content: content })
    end

    def add_assistant_message(content)
      unless !messages.empty? && @messages.last[:role] == "user"
        raise ChatHelper::MessageOrderError, "expecting user message"
      end

      @messages.push({ role: "assistant", content: content })
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    # Places a temporary cookie on user's browser containing
    # an encrypted version of the user's id
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def authenticate_user
    redirect_to(admin_path, danger: "Must be logged in to add books") unless logged_in?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<tr id="<%= book.id %>" aria-label="book row" class="text-inherit my-2">
  <td class="pb-2 pr-1 md:pr-0"><%= book.owner.name %></td>
  <td class="pb-2 pr-1 md:pr-0"><%= book.title.titleize %></td>
  <td class="pb-2 pr-1 md:pr-0"><%= book.author.name %></td>
  <td class="pb-2 pr-1 md:pr-0"><%= book.genres.map(&:name).join(", ") %></td>
  <% if logged_in? %>
  <td>
  <%= link_to book_edit_path(:id => book.id) do %>
    <svg class="pb-1 stroke-slate-500 hover:stroke-slate-700" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
      <g>
        <path d="M17 3C17.2626 2.73735 17.5744 2.52901 17.9176 2.38687C18.2608 2.24473 18.6286 2.17157 19 2.17157C19.3714 2.17157 19.7392 2.24473 20.0824 2.38687C20.4256 2.52901 20.7374 2.73735 21 3C21.2626 3.26264 21.471 3.57444 21.6131 3.9176C21.7553 4.26077 21.8284 4.62856 21.8284 5C21.8284 5.37143 21.7553 5.73923 21.6131 6.08239C21.471 6.42555 21.2626 6.73735 21 7L7.5 20.5L2 22L3.5 16.5L17 3Z" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
      </g>
    </svg>
  <% end %>
  </td>
  <% end %>
</tr>

app/views/books/add.html.erb
<% provide(:title, "Add Book") %>
<div class="mx-auto w-10/12 md:w-8/12 lg:w-6/12">
  <section id="top-matter">
    <h1 class="font-semibold text-2xl leading-tight tracking-tight text-slate-800">Add a book to the Collections</h1>
    <p class="leading-snug text-slate-800">Great! I can't wait to see what book you add to the Collections.</p>
  </section>
  <section id="add-book" class="mt-4">
    <%= form_with(url: book_path, method: :post, class: "flex flex-col justify-between gap-2") do |f| %>
      <section id="owner-field">
        <div>
          <%= f.label :owner, class: "text-sm font-medium leading-6 text-gray-900" %>
          <span class="text-slate-400 font-light">*</span>
        </div>
        <%= f.text_field :owner, required: true, list: "owner-options", autocomplete: "off", placeholder: "Select existing or type new owner", class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
        <datalist id="owner-options">
          <% Owner.all.each do |owner| %>
            <option value="<%= owner.name %>">
          <% end %>
        </datalist>
      </section>
      <section id="title-field">
        <div>
          <%= f.label :title, class: "text-sm font-medium leading-6 text-gray-900" %>
          <span class="text-slate-400 font-light">*</span>
        </div>
        <%= f.text_area :title, required: true, autocomplete: "off", placeholder: "Provide book title", class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
      </section>
      <section id="author-field">
        <div>
          <%= f.label :author, class: "text-sm font-medium leading-6 text-gray-900" %>
          <span class="text-slate-400 font-light">*</span>
        </div>
        <%= f.text_field :author, required: true, list: "author-options", autocomplete: "off", placeholder: "Select existing or type new author", class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
        <datalist id="author-options">
          <% Author.all.each do |author| %>
            <option value="<%= author.name %>">
          <% end %>
        </datalist>
      </section>
      <section id="genres-field">
        <div>
          <%= f.label :genres, class: "text-sm font-medium leading-6 text-gray-900" %>
          <span class="text-slate-400 font-light">*</span>
        </div>
        <%= f.text_field :genres, required: true, list: "genre-options", autocomplete: "off", placeholder: "Select existing or type new genre", class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
        <datalist id="genre-options">
          <% Genre.all.each do |genre| %>
            <option value="<%= genre.name %>">
          <% end %>
        </datalist>
      </section>
      <div class="mt-4 flex flex-col md:flex-row justify-between gap-2 md:gap-4">
        <%= link_to "Cancel", books_path, class: "basis-full min-h-11 p-1 rounded-md text-xs md:text-sm font-semibold text-gray-800 shadow-sm bg-gray-300 hover:bg-gray-400 cursor-pointer content-center text-center" %>
        <%= f.submit "Save", class: "basis-full min-h-11 p-1 rounded-md text-xs md:text-sm font-semibold text-white shadow-sm bg-green-800 hover:bg-green-700 cursor-pointer content-center text-center" %>
      </div>
    <% end %>
  </section>
</div>

app/views/books/edit.html.erb
<% provide(:title, "Edit Book") %>
<div class="mx-auto w-10/12 md:w-8/12 lg:w-6/12">
  <section id="top-matter">
    <div class="flex flex-row justify-between">
      <h1 class="font-semibold text-2xl leading-tight tracking-tight text-slate-800">Edit "<%= @book.title.titleize %>"</h1>
      <%= link_to book_remove_path(:id => @book.id) do %>
      <svg width="44" height="44" viewBox="0 0 44 44" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path class="fill-red-600 hover:fill-red-500" d="M0.5 22C0.5 10.1259 10.1259 0.5 22 0.5C33.8741 0.5 43.5 10.1259 43.5 22C43.5 33.8741 33.8741 43.5 22 43.5C10.1259 43.5 0.5 33.8741 0.5 22Z" fill="#EC221F"/>
        <path d="M14.5 17H16.1667M16.1667 17H29.5M16.1667 17L16.1667 28.6667C16.1667 29.1087 16.3423 29.5326 16.6548 29.8452C16.9674 30.1578 17.3913 30.3334 17.8333 30.3334H26.1667C26.6087 30.3334 27.0326 30.1578 27.3452 29.8452C27.6577 29.5326 27.8333 29.1087 27.8333 28.6667V17M18.6667 17V15.3334C18.6667 14.8913 18.8423 14.4674 19.1548 14.1548C19.4674 13.8423 19.8913 13.6667 20.3333 13.6667H23.6667C24.1087 13.6667 24.5326 13.8423 24.8452 14.1548C25.1577 14.4674 25.3333 14.8913 25.3333 15.3334V17M20.3333 21.1667V26.1667M23.6667 21.1667V26.1667" stroke="#F5F5F5" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>
      <% end %>
    </div>
    <p class="pt-2 leading-snug text-slate-800">Feel free to edit the deets or remove the book from the collection.</p>
  </section>
  <section id="edit-book" class="mt-4">
    <%= form_with(model: @book, url: book_edit_path(@book, id: @book.id), method: :put, class: "flex flex-col justify-between gap-2") do |f| %>
      <section id="owner-field">
        <div>
          <%= f.label :owner, class: "text-sm font-medium leading-6 text-gray-900" %>
          <span class="text-slate-400 font-light">*</span>
        </div>
        <%= f.text_field :owner, required: true, list: "owner-options", autocomplete: "off", value: "#{@book.owner.name}", placeholder: "Select existing or type new owner", class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
        <datalist id="owner-options">
          <% Owner.all.each do |owner| %>
            <option value="<%= owner.name %>">
          <% end %>
        </datalist>
      </section>
      <section id="title-field">
        <div>
          <%= f.label :title, class: "text-sm font-medium leading-6 text-gray-900" %>
          <span class="text-slate-400 font-light">*</span>
        </div>
        <%= f.text_area :title, required: true, autocomplete: "off", value: "#{@book.title.titleize}", placeholder: "Provide book title", class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
      </section>
      <section id="author-field">
        <div>
          <%= f.label :author, class: "text-sm font-medium leading-6 text-gray-900" %>
          <span class="text-slate-400 font-light">*</span>
        </div>
        <%= f.text_field :author, required: true, list: "author-options", autocomplete: "off", value: "#{@book.author.name}", placeholder: "Select existing or type new author", class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
        <datalist id="author-options">
          <% Author.all.each do |author| %>
            <option value="<%= author.name %>">
          <% end %>
        </datalist>
      </section>
      <section id="genres-field">
        <div>
          <%= f.label :genres, class: "text-sm font-medium leading-6 text-gray-900" %>
          <span class="text-slate-400 font-light">*</span>
        </div>
        <%= f.text_field :genres, required: true, list: "genre-options", autocomplete: "off", value: "#{@book.genres.map(&:name).join(', ')}", placeholder: "Select existing or type new genre", class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
        <datalist id="genre-options">
          <% Genre.all.each do |genre| %>
            <option value="<%= genre.name %>">
          <% end %>
        </datalist>
      </section>
      <div class="mt-4 flex flex-col md:flex-row justify-between gap-2 md:gap-4">
        <%= link_to "Cancel", books_path, class: "basis-full min-h-11 p-1 rounded-md text-xs md:text-sm font-semibold text-gray-800 shadow-sm bg-gray-300 hover:bg-gray-400 cursor-pointer content-center text-center" %>
        <%= f.submit "Save", class: "basis-full min-h-11 p-1 rounded-md text-xs md:text-sm font-semibold text-white shadow-sm bg-green-800 hover:bg-green-700 cursor-pointer content-center text-center" %>
      </div>
    <% end %>
  </section>
</div>

app/views/books/remove.html.erb
<% provide(:title, "Remove Book") %>
<div class="mx-auto w-10/12 md:w-8/12 lg:w-6/12">
  <section id="top-matter">
    <h1 class="font-semibold text-2xl leading-tight tracking-tight text-slate-800">Remove "<%= @book.title.titleize %>"?</h1>
    <p class="leading-snug text-slate-800">Are you sure? Adding "<%= @book.title.titleize %>" back to the collection will require re-entering the information.</p>
  </section>
  <section id="remove-book" class="mt-4">
    <%= form_with(url: book_remove_path(:id => @book.id), method: :delete, class: "flex flex-col justify-between gap-2") do |f| %>
      <div class="mt-4 flex flex-col md:flex-row justify-between gap-2 md:gap-4">
        <%= f.submit "Remove", class: "basis-full min-h-11 p-1 rounded-md text-xs md:text-sm font-semibold text-white shadow-sm bg-red-600 hover:bg-red-500 cursor-pointer content-center text-center" %>
        <%= link_to "Cancel", :back, class: "basis-full min-h-11 p-1 rounded-md text-xs md:text-sm font-semibold text-gray-800 shadow-sm bg-gray-300 hover:bg-gray-400 cursor-pointer content-center text-center" %>
      </div>
    <% end %>
  </section>
</div>

app/views/books/show.html.erb
<% provide(:title, "Collections") %>
<div class="mx-auto">
  <section id="top-matter">
    <h1 class="font-semibold text-2xl leading-tight tracking-tight text-slate-800">Browse our books</h1>
    <p class="leading-snug text-slate-800">The Churchill Library houses books from all our family members. Explore our books using the provided search and filters.</p>
  </section>
  <section id="search-and-filters" class="mt-4 flex flex-col md:flex-row justify-between gap-4">
    <%= form_with(url: books_path, method: :get, class: "basis-3/4 flex flex-col justify-between gap-2") do |f| %>
      <div class="relative">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg" class="inline absolute mt-4 ml-3">
          <path d="M13 13L10.1 10.1M11.6667 6.33333C11.6667 9.27885 9.27885 11.6667 6.33333 11.6667C3.38781 11.6667 1 9.27885 1 6.33333C1 3.38781 3.38781 1 6.33333 1C9.27885 1 11.6667 3.38781 11.6667 6.33333Z" stroke="#1E1E1E" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
        <%= f.search_field :title, placeholder: "Search by title...", value: params[:title], class: "w-full pl-8 rounded-full border border-solid border-slate-200 focus:border-transparent focus:shadow-none" %>
      </div>
      <div class="flex md:flex-row flex-col">
        <div class="w-full mr-0 md:mr-3">
          <%= f.label :owner, class: "block text-xs md:text-sm font-medium leading-6 text-gray-900" %>
          <%= select_tag :owner, options_from_collection_for_select(@owners, :id, :name, @owner&.id), include_blank: "All Owners", onchange: "this.form.requestSubmit()", class: "w-full rounded-lg border border-solid border-slate-200" %>
        </div>
        <div class="w-full mx-0 md:mx-2">
          <%= f.label :author, class: "block text-xs md:text-sm font-medium leading-6 text-gray-900" %>
          <%= select_tag :author, options_from_collection_for_select(@authors, :id, :name, @author&.id), include_blank: "All Authors", onchange: "this.form.requestSubmit()", class: "w-full rounded-lg border border-solid border-slate-200" %>
        </div>
        <div class="w-full ml-0 md:ml-3">
          <%= f.label :genre, class: "block text-xs md:text-sm font-medium leading-6 text-gray-900" %>
          <%= select_tag :genre, options_from_collection_for_select(@genres, :id, :name, @genre&.id), include_blank: "All Genres", onchange: "this.form.requestSubmit()", class: "w-full rounded-lg border border-solid border-slate-200" %>
        </div>
      </div>
    <% end %>
    <div class="basis-1/4 min-h-12 md:max-w-64 flex flex-row md:flex-col justify-end gap-2">
      <% if logged_in? %>
      <button id="ai-chat" class="basis-full py-2 md:py-0 border border-solid rounded-md text-xs md:text-sm font-semibold text-slate-600 shadow-sm border-green-600 hover:border-green-800 cursor-pointer disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:border-green-600" disabled>Chat with Librarian</button>
      <% else %>
      <button id="ai-chat" class="basis-full md:basis-12 py-2 md:py-0 rounded-md text-xs md:text-sm font-semibold text-white shadow-sm bg-green-800 hover:bg-green-700 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:bg-green-800" disabled>Chat with Librarian</button>
      <% end %>
      <% if logged_in? %>
      <%= link_to "Add Book", book_path, class: "basis-full p0 rounded-md text-xs md:text-sm font-semibold text-white shadow-sm bg-green-800 hover:bg-green-700 cursor-pointer content-center text-center" %>
      <% end %>
    </div>
  </section>
  <section id="books-table" class="mt-4">
    <table class="w-full table-auto md:table-fixed">
      <thead>
        <tr class="border-b border-solid border-slate-200 text-base md:text-lg text-left text-slate-800">
          <th class="w-2/12 font-medium text-inherit">Owner</th>
          <th class="w-4/12 font-medium text-inherit">Title</th>
          <th class="w-3/12 font-medium text-inherit">Author</th>
          <th class="w-3/12 font-medium text-inherit">Genres</th>
        </tr>
      </thead>
      <tbody class="font-light text-sm md:text-base text-slate-800 space-y-8 md:space-y-6 lg:space-y-4">
      <%= render @books %>
      </tbody>
    </table>
    <%= will_paginate @books, size: 10, class: "mt-2 flex flex-row justify-center text-sm md:text-base text-slate-600 *:mx-2 [&_em]:text-white [&_em]:bg-slate-900 [&_em]:px-2 [&_em]:rounded-lg [&_span]:cursor-not-allowed [&_span]:text-slate-400" %>
  </section>
</div>

app/views/collections/add.html.erb
<% provide(:title, "Add Book") %>
<div class="mx-auto">
  <section id="top-matter">
    <h1 class="font-semibold text-2xl leading-tight tracking-tight text-slate-800">Add a book to the Collections</h1>
    <p class="leading-snug text-slate-800">Great! I can't wait to see what book you add to the Collections.</p>
  </section>
  <section id="add-book" class="mt-4">
    <%= form_with(url: book_path, method: :post, class: "flex flex-col justify-between gap-2") do |f| %>
      <div>
        <%= f.label :owner, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <%= f.text_field :owner, class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
      </div>
      <div>
        <%= f.label :title, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <%= f.text_area :title, class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
      </div>
      <div>
        <%= f.label :author, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <%= f.text_field :author, class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
      </div>
      <div>
        <%= f.label :genres, class: "block text-sm font-medium leading-6 text-gray-900" %>
        <%= f.text_field :genres, class: "w-full border border-solid border-slate-200 rounded-md focus:border-transparent focus:shadow-none" %>
      </div>
      <div class="mt-4 flex flex-col md:flex-row justify-between gap-2 md:gap-4">
        <%= link_to "Cancel", collections_path, class: "basis-full min-h-11 p-1 rounded-md text-xs md:text-sm font-semibold text-gray-800 shadow-sm bg-gray-300 hover:bg-gray-400 cursor-pointer content-center text-center" %>
        <%= f.submit "Save", class: "basis-full min-h-11 p-1 rounded-md text-xs md:text-sm font-semibold text-white shadow-sm bg-green-800 hover:bg-green-700 cursor-pointer content-center text-center" %>
      </div>
    <% end %>
  </section>
</div>

app/views/library/home.html.erb
<div class="mx-auto">
  <div class="relative isolate px-6 lg:px-8">
    <div class="mx-auto max-w-2xl">
      <div class="text-center">
        <h2 class="object-center text-4xl font-bold tracking-tight text-grey sm:text-6xl">Welcome to the Library</h2>
        <p class="mt-6 text-lg leading-8 text-gray-500">The Churchill Library is a hodgepodge, thrown-together rigamarole filled with excitement, tears, and love. Enjoy your stay.</p>
      </div>
    </div>
  </div>
</div>